kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: dynatrace-oneagent-operator
  namespace: dynatrace
  labels:
    dynatrace: operator
    operator: oneagent
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-account-dynatrace-oneagent-operator
  namespace: dynatrace
  labels:
    dynatrace: operator
    operator: oneagent
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: dynatrace-oneagent-operator
  apiGroup: rbac.authorization.k8s.io
